const DEFAULT_LAYOUT_MODE = 'stack';

const DEFAULT_OPTIONS = {
  startIndex: 0,
  layoutMode: DEFAULT_LAYOUT_MODE,
  autoRotate: false,
  autoRotateInterval: 3000,
  swipeThreshold: 50,
  dragThreshold: 80,
  preloadRange: 2,
  enableKeyboard: true,
  enableWheel: true,
  enableTouch: true,
  enableMouse: true
};

const SELECTORS = {
  carousel: '#myCarousel',
  nav: '.peek-carousel__nav',
  controls: '.peek-carousel__controls',
  counter: '.peek-carousel__counter',
  prevBtn: '.prev-btn',
  layoutButton: '.button__group-item',
  layoutButtonActive: '.button__group-item--active[data-layout]',
  layoutModeGroup: '[aria-label="Layout mode selection"]',
  controlsToggle: '.controls__toggle',
  controlsClose: '.controls__close',
  controlsPanel: '.controls__panel',
  keyboardToggle: '.keyboard__toggle',
  keyboardPanel: '.keyboard__panel',
  mouseToggle: '.mouse__toggle',
  mousePanel: '.mouse__panel',
};

const AUTO_GENERATED_SELECTORS = [
  SELECTORS.nav,
  SELECTORS.controls,
  SELECTORS.counter,
];

const TOGGLEABLE_UI_IDS = [
  'showNavigation',
  'showCounter',
  'showIndicators',
  'showAutoRotateButton'
];

const PANELS = [
  { name: 'controls', panelClass: 'controls__panel', toggleClass: 'controls__toggle' },
  { name: 'keyboard', panelClass: 'keyboard__panel', toggleClass: 'keyboard__toggle' },
  { name: 'mouse', panelClass: 'mouse__panel', toggleClass: 'mouse__toggle' },
  { name: 'share', panelClass: 'share__panel', toggleClass: 'share__toggle' }
];

let elements = {};
let panelElements = {};
let carousel = null;

const buildCarouselOptions = (currentIndex = DEFAULT_OPTIONS.startIndex) => {
  const layoutMode = document.querySelector(SELECTORS.layoutButtonActive)?.dataset.layout || DEFAULT_LAYOUT_MODE;

  return {
    ...DEFAULT_OPTIONS,
    startIndex: currentIndex,
    layoutMode,
    showNavigation: elements.showNavigation?.checked ?? true,
    showCounter: elements.showCounter?.checked ?? true,
    showIndicators: elements.showIndicators?.checked ?? true,
    showAutoRotateButton: elements.showAutoRotateButton?.checked ?? true,
  };
};

const removeAutoGeneratedElements = (container) => {
  for (const selector of AUTO_GENERATED_SELECTORS) {
    const element = container.querySelector(selector);
    if (element) element.remove();
  }
};

const reinitializeCarousel = () => {
  const currentIndex = carousel.state.currentIndex;
  carousel.destroy();
  removeAutoGeneratedElements(carousel.container);
  carousel = new PeekCarousel(SELECTORS.carousel, buildCarouselOptions(currentIndex));
  moveCounterToNavigation();
};

const closeAllPanels = (exceptPanelName = null) => {
  for (const name in panelElements) {
    if (name === exceptPanelName) continue;

    const { panel, toggle, activeClass } = panelElements[name];
    panel?.classList.remove(activeClass);
    toggle?.setAttribute('aria-expanded', 'false');
  }
};

const createTogglePanel = (panelName) => {
  return () => {
    const cachedPanel = panelElements[panelName];
    if (!cachedPanel) return;

    const { panel, toggle, activeClass } = cachedPanel;
    const isActive = panel.classList.toggle(activeClass);

    toggle?.setAttribute('aria-expanded', isActive);

    if (isActive) {
      closeAllPanels(panelName);
    }
  };
};

const toggleControlsPanel = createTogglePanel('controls');
const toggleKeyboardPanel = createTogglePanel('keyboard');
const toggleMousePanel = createTogglePanel('mouse');
const toggleSharePanel = createTogglePanel('share');

const handleLayoutModeChange = (buttonGroup, clickedButton) => {
  const buttons = buttonGroup.querySelectorAll(SELECTORS.layoutButton);
  for (const btn of buttons) {
    btn.classList.remove('button__group-item--active');
    btn.setAttribute('aria-pressed', 'false');
  }

  clickedButton.classList.add('button__group-item--active');
  clickedButton.setAttribute('aria-pressed', 'true');

  const layoutMode = clickedButton.dataset.layout;
  carousel.options.layoutMode = layoutMode;
  carousel.updateLayoutClass();

  // [데모용] stack 모드에서 transform 초기화
  if (layoutMode === DEFAULT_LAYOUT_MODE) {
    carousel.elements.carousel.style.transform = 'none';
  }

  carousel.animator.updateCarousel();
};

const attachEventListeners = () => {
  const toggleBtn = document.querySelector(SELECTORS.controlsToggle);
  const keyboardToggleBtn = document.querySelector(SELECTORS.keyboardToggle);
  const mouseToggleBtn = document.querySelector(SELECTORS.mouseToggle);
  const shareToggleBtn = document.querySelector('.share__toggle');
  const closeBtn = document.querySelector(SELECTORS.controlsClose);
  const layoutModeGroup = document.querySelector(SELECTORS.layoutModeGroup);

  toggleBtn?.addEventListener('click', toggleControlsPanel);
  keyboardToggleBtn?.addEventListener('click', toggleKeyboardPanel);
  mouseToggleBtn?.addEventListener('click', toggleMousePanel);
  shareToggleBtn?.addEventListener('click', toggleSharePanel);
  closeBtn?.addEventListener('click', toggleControlsPanel);

  layoutModeGroup?.addEventListener('click', (event) => {
    const clickedButton = event.target.closest(SELECTORS.layoutButton);
    if (clickedButton) {
      handleLayoutModeChange(layoutModeGroup, clickedButton);
    }
  });

  for (const id of TOGGLEABLE_UI_IDS) {
    elements[id]?.addEventListener('change', reinitializeCarousel);
  }
};

const cacheElements = () => {
  elements = TOGGLEABLE_UI_IDS.reduce((acc, id) => {
    acc[id] = document.getElementById(id);
    return acc;
  }, {});

  panelElements = PANELS.reduce((acc, config) => {
    acc[config.name] = {
      panel: document.querySelector(`.${config.panelClass}`),
      toggle: document.querySelector(`.${config.toggleClass}`),
      activeClass: `${config.panelClass}--active`,
    };
    return acc;
  }, {});
};

// [데모용] 카운터를 네비게이션 내부로 이동 (이전 버튼 옆에 배치)
const moveCounterToNavigation = () => {
  const nav = carousel.container.querySelector(SELECTORS.nav);
  if (!nav) return;

  const counter = carousel.container.querySelector(SELECTORS.counter);
  if (!counter) return;

  const prevBtn = nav.querySelector(SELECTORS.prevBtn);
  if (!prevBtn) return;

  nav.insertBefore(counter, prevBtn.nextSibling);
};

const init = () => {
  cacheElements();
  carousel = new PeekCarousel(SELECTORS.carousel, buildCarouselOptions());
  moveCounterToNavigation();
  attachEventListeners();
};

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
